title: Site
unlisted: true

columns:

  - width: 1/2
    sections:
      listed:
        headline: Menu
        type: pages
        status: listed

      unlisted:
        headline: Unlisted
        type: pages
        status: unlisted

      drafts:
        headline: Drafts
        type: pages
        status: draft
        templates:
          - default
          - home
          - link
          - press

  - width: 1/2
    sections:
      fields:
        type: fields
        fields:
          logo_head:
            type: headline
            numbered: false
            label: Logo
          logo_top:
            label: Header
            type: files
            layout: cards
            query: site.images
            max: 1
            help: Appears on all pages except Petitions
            width: 1/3
          logo_foot:
            label: Footer
            type: files
            layout: cards
            query: site.images
            max: 1
            width: 1/3
          social_head:
            type: headline
            numbered: false
            label: Social Media
          fbtext:
            label: Facebook Site Description
            type: textarea
            buttons: false
            width: 2/3
          fbimg:
            label: Thumbnail
            type: files
            layout: cards
            query: site.images
            max: 1
            width: 1/3
          twtext:
            label: Twitter Site Description
            type: textarea
            buttons: false
            width: 2/3
          twimg:
            label: Image
            type: files
            layout: cards
            query: site.images
            max: 1
            width: 1/3
