title: Site
unlisted: true

columns:
  - width: 2/3
    sections:
      listed:
        headline: Menu
        type: pages
        status: listed

      unlisted:
        headline: Unlisted
        type: pages
        status: unlisted

      drafts:
        headline: Drafts
        type: pages
        status: draft

  - width: 1/3
    sections:
      fields:
        type: fields
        fields:
          logo:
            type: files
            layout: cards
            query: page.images
            max: 1
